# Discussion

Using the 2023 survey of occupational injuries, I found that non-office workers are about 2.2 times more likely to suffer an injury from a fall and also 2.8 times more likely to slip without falling than an office worker \[\@SurveyOccupationalInjuries\]. The evidence found using the US Bureau of Labor Statistics data supports this overwhelming conclusion opposite of the original claim. While the original CDC data was unavailable to public access, the available data used for this analysis is reliable and established.

The evidence from BLS directly opposes the original claim. It suggests that office workers are not at a higher risk of suffering injuries from falls than non-office workers. Generalizing to all types of injuries, I found that non-office industries have 3.5 times the number of recordable injuries compared to office industries \[\@TABLE1Incidence\]. Similarly, the same data revealed that non-office industries had 3.6 times the number of recordable injuries requiring days away from work. The rate of recordable injuries and total recordable injuries with time away from work suggests that non-office workers are more likely to be injured at work and that the severity distribution of these injuries is higher than those of office workers. This evidence builds a strong case against any claim that office workers are likelier to suffer an injury from a fall than non-office workers.

Here is another way to think about this main conclusion: If a construction site and an accounting office have the same number of falls, the severity of those falls is likely to vary drastically. In many ways, we would hope to see fewer falls on the construction site than in the office because of the associated risk in the setting. According to the CDC, we see the highest number of workplace falls and fall injuries in construction, educational and health services, ambulance services, building maintenance, and transportation services \[\@cdcFallsWorkplace2024\].

## Limitations

We should consider that many industries filled predominantly by office jobs are partially exempt from OSHA record keeping because of the low incident rate \[\@RecordkeepingNonMandatoryAppendix\]. Low report rates may lead to a bias in the data regarding how many fall injuries are reported in office industries or only reporting severe injuries. On the other hand, many office workers may be less conscious of OSHA regulations, increasing the likelihood of falls. Both these factors may lead to different kinds of bias in the data, which could be addressed in the future by more focused studies into office workplace injuries and stress on following OSHA safety regulations in all workplaces.

We should acknowledge that the definition of "office" jobs and industries is sometimes subjective, and categorizing all the recognized NAICS industries into two groups is not a perfect system. Some jobs, such as real estate and administration support, have subcategory industries that vary significantly between office and non-office. For example, real estate may require workers to have an office, but it also includes extensive work outside an office. The administration support industry includes office support, security detail, and janitorial services, which likely have higher rates of injury. While there could be a debate on whether some industries are included, the evidence is conclusive enough for the variability not to make a significant difference. Future work could compare results from different combinations of NAICS codes to see how much the conclusion changes or allow the time to divide all 1074 industries into the two categories meticulously.

## Recommended Actions

Despite the evidence that office workplaces are at much lower risk for falls and overall injuries, the second most common injury in offices still falls on the same level \[\@SurveyOccupationalInjuries\]. Given that an office industry reports an injury, there is about a 17.76% chance that the injury is a fall on the same level. The CDC cites the following reasons as the most common causes of falls in the workplace \[\@cdcFallsWorkplace2024\]:

-   Unprotected edges

-   Unsafely positioned ladders

-   Misused fall protection

-   Water, grease, and other contaminants on the floor

-   Clutter and tripping hazards in walkways

-   Irregularities in the floor and wall openings

Appropriate steps taken in an office could significantly reduce the risk of any workers falling, such as safety training, proper use of ladders, and cleaning up/labeling any floor area with liquid on it. It is a company's responsibility to ensure all parts of the building are using accessible architecture (ramps, elevators, wide doorways) so no employees are put in a position to take unnecessary risks.

This report concludes with strong evidence to say that office workers are not at a higher risk of suffering an injury from a fall than non-office workers. That said, office workers risk injury if proper safety regulations are not followed. Every company highly values the well-being of its employees and should always take the appropriate steps to ensure a comfortable and safe work environment.
