---
title: "Draft: Intro/Conclusions"
---

# Introduction

Safety in the workplace is the most important priority for any company to have. No matter the industry, location, or project, taking measures to ensure workers are not at risk of injury is a necessity. It is both the responsibility of management and workers to stay informed and up-to-date with safety regulations. These rules and regulations can look very different industry to industry. In an office setting, some may think safety is not a prioritized concern, but that is far from the truth. Falls are the leading cause of injuries in an office setting @SurveyOccupationalInjuries, and it is important to understand the risks, causes, and ways to reduce the probability of this type of injury.

A 2012 article from The Albert Einstein College of Medicine cited the Center of Disease Control and Prevention with the claim that "office workers are 2 to 2.5 times more likely to suffer an injury from a fall than non-office workers" @WhatAreTop2012. An analysis into this claim may reveal insight on the source and interpretation of the original CDC data. It is possible this claim has two slightly different meanings:

1.  Office workers are more likely to suffer an injury given they had a fall compared to non-office workers.

2.  Office workers are more likely to have a fall that results in an injury compared to non-office workers.

In the original claim and this report, any reference to "falls" explicitly means falls on the same level, and excludes injuries resulting from falls to a different level (which are reported in separate categories in CDC and US Bureau survey data). The following analysis will compare the number of falls between office and non-office workers, and also the number of falls resulting in injury between the two groups. The difference between the two interpretations lead to two separate concerns: are office workers at higher risk of falling or higher risk of suffering an injury from a fall? It is also important to remember this data and claim is from 2012 at the latest, and the workplace has changed very much in the last decade.

While the claim may have held truth at the time, based on my research and analysis of 2023 CDC data, this claim is false in both interpretations. Non-office workers are about 1.5 times more likely to suffer an injury from a fall than an office worker.

# Conclusion

The evidence found using the US Bureau of Labor Statistics data supports an overwhelming conclusion that is opposite than that of the original claim. While the original CDC data was unavailable to public access, the available data used for this analysis is reliable and established.

Using the 2023 survey of occupational injuries, I found that non-office workers are about 1.5 times more likely to suffer an injury from a fall, and also 1.4 times more likely to slip without falling than an office worker @SurveyOccupationalInjuries. This evidence directly opposes the original claim, and suggests that office workers are not at a higher risk of suffering injuries from falls than non-office workers. Generalizing to all types of injuries, I found that non-office industries have 3.3 times the number of recordable injuries compared to office industries @TABLE1Incidence. Similarly, the same data revealed that non-office industries had 3.3 times the number of recordable injuries that specifically required days away from work. The rate of recordable injuries and total recordable injuries with time away from work suggests that not only are non-office workers more likely to be injuried at work, but also that the severity distribution of these injuries are higher than the injuries of office workers. This evidence combined builds a strong case against any claim that office workers are more likely to suffer an injury from a fall than a non-office worker.

Here is another way to think about this main conclusion: If a construction site and an accounting office have the same number of falls, the severity of those falls likely vary drastically. In many ways, we would hope to see less falls in the construction site than the office, because of the associated risk in the setting. According to the CDC , we see the highest number of workplace falls and fall injuries in construction, educational and health services, ambulance services, building maintenance, and transportation services @cdcFallsWorkplace2024.

We should consider the fact that many industries filled predominantly by office jobs are partially exempt from OSHA record keeping because of the low incident rate @RecordkeepingNonMandatoryAppendix. This may lead to a bias in the data regarding how many fall injuries are reported in office industries. On the other hand, many office workers may be less conscious of OSHA regulations, and therefore increase the likelihood of falls. Both these factors may lead to diffferent kinds of bias in the data, which could be addressed in the future by more focused studies into office workplace injuries, and also a stress on following OSHA safety regulations in all workplaces.

It should be acknowledged that the definition of "office" jobs and industries is, at times, subjective, and categorizing all the recognized NAICS industries into the two groups is not a perfect system. Some jobs, such as real estate, may require workers to have an office but also include extensive work outside an office. While there could be a debate on some industries being included or not, I believe the evidence is conclusive enough for the variability to not make a significant difference. Future work could compare results from different combinations of NAICS codes to see by how much the final conclusion changes.

Despite the evidence that office workplaces are at much lower risk for falls and overall injuries, the leading injury in offices is still slips and falls. The CDC cites the following reasons as the most common causes of falls in the workplace @cdcFallsWorkplace2024:

-   Unprotected edges

-   Unsafely positioned ladders

-   Misused fall protection

-   Water, grease, and other contaminants on the floor

-   Clutter and tripping hazards in walkways

-   Irregularities in the floor and wall openings

Appropriate steps taken in an office could greatly reduce the risk of any workers falling, such as safety training, proper use of ladders, and cleaning up/labeling any floor area with liquid on it. It is a company's responsibility to ensure all parts of the building are using accessible archetecture (ramps, elevators, wide doorways, etc.) so no employees are put in a position to take unnecessary risks.

This report concludes with strong evidence to say that office workers are not at a higher risk to suffer an injury from a fall than non-office workers. That being said, office workers still face the risk of injury if proper safety regulations are not followed. Every company highly values the wellbeing of their employees, and should always take the proper steps to ensure a comfortable and safe work environment.
